version: 0.2

phases:
  build:
    commands:
      - nuget restore AWSTestNancy.sln
      - nuget install MSBuild.Microsoft.VisualStudio.Web.targets -Version 14.0.0.3
      - msbuild AWSTestNancy.sln /t:Package /p:DeployIisAppPath="Default Web Site" /p:PackageLocation=.\NancyPackage.zip /p:Configuration=Release

artifacts:
  files:
    - AWSTestNancy\NancyPackage.zip
